{
 "title": "Bathroom",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<h1> \n<center>\n<font color=\"#70ee3a\"> BATHROOM </font>\n</center>\n</h1>"
   }
  },
  {
   "title": "Temperature",
   "type": "briangann-gauge-panel",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "dataset": "db_home_automation",
     "rawSql": "SELECT UNIX_TIMESTAMP(Timestamp) as time, Temperature FROM db_home_automation.room_bathroom ORDER BY time DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "briangann-gauge-panel",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "dataset": "db_home_automation",
     "rawSql": "SELECT UNIX_TIMESTAMP(Timestamp) as time, Humidity FROM db_home_automation.room_bathroom ORDER BY time DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Room Data",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "dataset": "db_home_automation",
     "rawSql": "SELECT\r\n  UNIX_TIMESTAMP(Timestamp) as time,\r\n  Temperature, Humidity\r\nFROM room_bathroom\r\nWHERE $__timeFilter(Timestamp)\r\nORDER BY Timestamp ASC\r\n"
    }
   ]
  },
  {
   "title": "Ventilation Fan",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "dataset": "db_home_automation",
     "rawSql": "SELECT\r\n  UNIX_TIMESTAMP(Timestamp) as time,\r\n  Fan_Vib_X, Fan_Vib_Y, Fan_Vib_Z\r\n\r\nFROM room_bathroom_zigbee\r\nWHERE $__timeFilter(Timestamp)\r\nORDER BY Timestamp ASC\r\n\r\n"
    }
   ]
  },
  {
   "title": "Ventilation Fan",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "dataset": "db_home_automation",
     "rawSql": "SELECT\r\n  UNIX_TIMESTAMP(Timestamp) as time,\r\n  (Fan_Vib_X + Fan_Vib_Y + Fan_Vib_Z ) / 3 as mean_xyz\r\n  #Fan_Vib_X, Fan_Vib_Y, Fan_Vib_Z \r\n  #MAX(Fan_Vib_X) as max_x\r\nFROM room_bathroom_zigbee\r\nWHERE $__timeFilter(Timestamp)\r\nORDER BY Timestamp ASC \r\n\r\n\r\n"
    }
   ]
  }
 ]
}