{
 "title": "Outdoor_data",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "Air Pollution [ug/m3]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  UNIX_TIMESTAMP(Timestamp) as time,\r\n  PM1_out, PM2_5_out, PM10_out\r\nFROM generic_outside_particulate_matter\r\nWHERE $__timeFilter(Timestamp)\r\nORDER BY Timestamp ASC \r\n"
    }
   ]
  },
  {
   "title": "Air Pollution [ug/m3]",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "db_home_automation",
     "rawSql": "SELECT UNIX_TIMESTAMP(Timestamp) as time, PM1_out, PM2_5_out, PM10_out \r\nFROM generic_outside_particulate_matter\r\nORDER BY Timestamp DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Temp [°C] / Humidity [%]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 20, "x": 0, "y": 8 },
   "targets": [
    {
     "dataset": "db_home_automation",
     "rawSql": "SELECT\r\n  UNIX_TIMESTAMP(Timestamp) as time,\r\n  Temperature, Humidity\r\nFROM generic_outside_conditions\r\nWHERE $__timeFilter(Timestamp)\r\nORDER BY Timestamp ASC \r\n"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "briangann-gauge-panel",
   "gridPos": { "h": 6, "w": 2, "x": 20, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "dataset": "db_home_automation",
     "rawSql": "SELECT UNIX_TIMESTAMP(Timestamp) as time, Temperature FROM db_home_automation.generic_outside_conditions ORDER BY Timestamp DESC LIMIT 1\r\n"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "briangann-gauge-panel",
   "gridPos": { "h": 6, "w": 2, "x": 22, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "dataset": "db_home_automation",
     "rawSql": "SELECT UNIX_TIMESTAMP(Timestamp) as time, Humidity FROM db_home_automation.generic_outside_conditions ORDER BY Timestamp DESC LIMIT 1\r\n\r\n"
    }
   ]
  },
  {
   "title": "Pressure [hPa]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dataset": "db_home_automation",
     "rawSql": "SELECT\r\n  UNIX_TIMESTAMP(Timestamp) as time, Pressure\r\nFROM generic_outside_conditions\r\nWHERE $__timeFilter(Timestamp)\r\nORDEr BY Timestamp ASC \r\n"
    }
   ]
  },
  {
   "title": "Pressure [hPa]",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "db_home_automation",
     "rawSql": "SELECT Pressure FROM db_home_automation.generic_outside_conditions ORDER BY Timestamp DESC LIMIT 1;"
    }
   ]
  }
 ]
}