{
 "title": "Bed room",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<h1>\n  <center>\n<font color=\"#70ee3a\"> BED ROOM </font>\n</center>\n</h1>"
   }
  },
  {
   "title": "Room Data",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 20, "x": 0, "y": 2 },
   "targets": [
    {
     "dataset": "db_home_automation",
     "rawSql": "SELECT\r\n  UNIX_TIMESTAMP(Timestamp) as time,\r\n  Temperature, Humidity\r\nFROM room_bedroom\r\nWHERE $__timeFilter(Timestamp)\r\nORDER BY Timestamp ASC \r\n"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "briangann-gauge-panel",
   "gridPos": { "h": 6, "w": 2, "x": 20, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "dataset": "db_home_automation",
     "rawSql": "SELECT UNIX_TIMESTAMP(Timestamp) as time, Temperature FROM db_home_automation.room_bedroom ORDER BY time DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "briangann-gauge-panel",
   "gridPos": { "h": 6, "w": 2, "x": 22, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "dataset": "db_home_automation",
     "rawSql": "SELECT UNIX_TIMESTAMP(Timestamp) as time, Humidity FROM db_home_automation.room_bedroom ORDER BY time DESC LIMIT 1\r\n\r\n"
    }
   ]
  },
  {
   "title": "Air Pollution [ug/m3]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  UNIX_TIMESTAMP(Timestamp) as time,\r\n  PM1_in, PM2_5_in, PM10_in\r\nFROM room_bedroom\r\nWHERE $__timeFilter(Timestamp)\r\nORDER BY Timestamp ASC \r\n"
    }
   ]
  },
  {
   "title": "Air Pollution [ug/m3]",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "db_home_automation",
     "rawSql": "SELECT UNIX_TIMESTAMP(Timestamp) as time, PM1_in, PM2_5_in, PM10_in \r\nFROM db_home_automation.room_bedroom\r\nORDER BY Timestamp DESC LIMIT 1\r\n\r\n"
    }
   ]
  }
 ]
}