{
 "title": "Electrical",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Phase L1",
   "type": "briangann-gauge-panel",
   "gridPos": { "h": 7, "w": 4, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dataset": "db_home_automation",
     "rawSql": "SELECT UNIX_TIMESTAMP(Timestamp) as time, L1 FROM db_home_automation.generic_current_integral ORDER BY time DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Phase L2",
   "type": "briangann-gauge-panel",
   "gridPos": { "h": 7, "w": 4, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dataset": "db_home_automation",
     "rawSql": "SELECT UNIX_TIMESTAMP(Timestamp) as time, L2 FROM db_home_automation.generic_current_integral ORDER BY time DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Phase L3",
   "type": "briangann-gauge-panel",
   "gridPos": { "h": 7, "w": 4, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dataset": "db_home_automation",
     "rawSql": "SELECT UNIX_TIMESTAMP(Timestamp) as time, L3 FROM db_home_automation.generic_current_integral ORDER BY time DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Energy usage [As]",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "dataset": "db_home_automation",
     "rawSql": "SELECT\r\n  UNIX_TIMESTAMP(Timestamp) as time,\r\n  L1, L2, L3\r\nFROM generic_current_integral\r\nWHERE $__timeFilter(Timestamp)\r\nORDER BY Timestamp ASC\r\n\r\n"
    }
   ]
  }
 ]
}