{
 "title": "Kitchen",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<h1>\n<center>\n<font color=\"#70ee3a\"> KITCHEN </font>\n</center>\n</h1>"
   }
  },
  {
   "title": "Temperature",
   "type": "briangann-gauge-panel",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "dataset": "db_home_automation",
     "rawSql": "SELECT UNIX_TIMESTAMP(Timestamp) as time, Temperature FROM db_home_automation.room_kitchen ORDER BY time DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Room Data",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 21, "x": 3, "y": 2 },
   "targets": [
    {
     "dataset": "db_home_automation",
     "rawSql": "SELECT\r\n  UNIX_TIMESTAMP(Timestamp) as time,\r\n  Temperature, Humidity\r\nFROM room_kitchen\r\n WHERE $__timeFilter(Timestamp) ORDER BY Timestamp ASC"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "briangann-gauge-panel",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "dataset": "db_home_automation",
     "rawSql": "SELECT UNIX_TIMESTAMP(Timestamp) as time, Humidity FROM db_home_automation.room_kitchen ORDER BY time DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "number of motions detected",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "db_home_automation",
     "rawSql": "SELECT COUNT(*)\r\nFROM room_kitchen as curr\r\nWHERE curr.Motion = 1 and $__timeFilter(Timestamp)\r\nAND (\r\n    SELECT Motion\r\n    FROM room_kitchen prev\r\n    WHERE prev.Timestamp < curr.Timestamp\r\n    ORDER BY Timestamp DESC\r\n    LIMIT 1\r\n) = 0;"
    }
   ]
  },
  {
   "title": "Motion Presence",
   "type": "state-timeline",
   "gridPos": { "h": 3, "w": 21, "x": 3, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT \r\n      UNIX_TIMESTAMP(Timestamp) as time,\r\n      Motion as motion_kitchen\r\nFROM db_home_automation.room_kitchen WHERE $__timeFilter(Timestamp) ORDER BY Timestamp ASC"
    }
   ]
  },
  {
   "title": "number of fridge door  openings",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "db_home_automation",
     "rawSql": "SELECT COUNT(*)\r\nFROM room_kitchen_zigbee as curr\r\nWHERE curr.Fridge_Door_Status = 1 and $__timeFilter(Timestamp)\r\nAND (\r\n    SELECT Fridge_Door_Status\r\n    FROM room_kitchen_zigbee prev\r\n    WHERE prev.Timestamp < curr.Timestamp\r\n    ORDER BY Timestamp DESC\r\n    LIMIT 1\r\n) = 0;"
    }
   ]
  },
  {
   "title": "Fridge Door Status",
   "type": "state-timeline",
   "gridPos": { "h": 3, "w": 21, "x": 3, "y": 13 },
   "targets": [
    {
     "dataset": "db_home_automation",
     "rawSql": "SELECT \r\n      UNIX_TIMESTAMP(Timestamp) as time,\r\n      Fridge_Door_Status as door_status\r\nFROM db_home_automation.room_kitchen_zigbee WHERE $__timeFilter(Timestamp) ORDER BY Timestamp ASC"
    }
   ]
  },
  {
   "title": "Fridge Data",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 21, "x": 3, "y": 16 },
   "targets": [
    {
     "dataset": "db_home_automation",
     "rawSql": "SELECT\r\n  UNIX_TIMESTAMP(Timestamp) as time,\r\n  Freezer_Temperature, Fridge_Temperature, Fridge_Humidity\r\nFROM room_kitchen_zigbee\r\n WHERE $__timeFilter(Timestamp) ORDER BY Timestamp ASC"
    }
   ]
  }
 ]
}