{
 "title": "Living room",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<h1>\n<center>\n<font color=\"#70ee3a\"> LIVING ROOM </font>\n</center>\n</h1>"
   }
  },
  {
   "title": "Motion Presence",
   "type": "state-timeline",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {
     "rawSql": "SELECT \r\n      UNIX_TIMESTAMP(Timestamp) as time,\r\n      Motion as motion_living\r\nFROM db_home_automation.room_living\r\nWHERE $__timeFilter(Timestamp)\r\nORDER BY Timestamp ASC "
    }
   ]
  },
  {
   "title": "Room Data",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 5 },
   "targets": [
    {
     "dataset": "db_home_automation",
     "rawSql": "SELECT\r\n  UNIX_TIMESTAMP(Timestamp) as time,\r\n  Temperature, Humidity\r\nFROM room_living\r\nWHERE $__timeFilter(Timestamp)\r\nORDER BY Timestamp ASC \r\n"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "briangann-gauge-panel",
   "gridPos": { "h": 8, "w": 2, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "dataset": "db_home_automation",
     "rawSql": "SELECT UNIX_TIMESTAMP(Timestamp) as time, Temperature FROM db_home_automation.room_living ORDER BY time DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "briangann-gauge-panel",
   "gridPos": { "h": 8, "w": 2, "x": 22, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "dataset": "db_home_automation",
     "rawSql": "SELECT Humidity FROM db_home_automation.room_living"
    }
   ]
  },
  {
   "title": "Air Pollution [ug/m3]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 13 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  UNIX_TIMESTAMP(Timestamp) as time,\r\n  PM1, PM2_5, PM10\r\nFROM room_living\r\nWHERE $__timeFilter(Timestamp)\r\nORDER BY Timestamp ASC \r\n"
    }
   ]
  },
  {
   "title": "Air Pollution [ug/m3]",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "db_home_automation",
     "rawSql": "SELECT UNIX_TIMESTAMP(Timestamp) as time, PM1, PM2_5, PM10 \r\nFROM db_home_automation.room_living\r\nORDER BY Timestamp DESC LIMIT 1\r\n\r\n\r\n"
    }
   ]
  }
 ]
}